package com.company.Task_12;

// TASK 12. Source (in Russian) - http://euler.jakumo.org/problems.html
//
//The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
//1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
//Let us list the factors of the first seven triangle numbers:
// 1: 1
// 3: 1,3
// 6: 1,2,3,6
//10: 1,2,5,10
//15: 1,3,5,15
//21: 1,3,7,21
//28: 1,2,4,7,14,28
//We can see that 28 is the first triangle number to have over five divisors.
//What is the value of the first triangle number to have over fifty divisors?

public class Task_12 {

    public static void main(String[] args) {
        int triangleNumber = 0;
        int n = 1;
        int num = 0;
        s: for (int i = 0; i <= n; i++) {
            triangleNumber += i;
            for (int b = 1; b <= triangleNumber; b++) {
                if ((triangleNumber % b) == 0) {
                    num++;
                }
            } if(num == 50) {System.out.println("первое треугольное число которое имеет 50 делителей: " + triangleNumber); break s; }
            else {n++; num = 0;}
        }


    }
}
